[build]
target = "powerpc-nintendo-wii.json"
rustflags = ["-C", "link-arg=-Trevolution.ld", "-C", "link-arg=-nostartfiles", "-C", "link-arg=-nostdlib"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
